#ifndef ASSETS_CONSTANTS_H
#define ASSET_CONSTANTS_H

// game objects
#define SHIPTEXTUREID 1
#define BULLETTEXTUREID 2
#define LEVEL1TEXTUREID 3
#define ENEMYTEXTUREID 4

// menus
#define TITLETEXTUREID 1000
#define VICTORYTEXTUREID 1001

// UI textures
#define BASICBUTTONTEXTUREID 2000

// sounds
#define BASICSHOTSOUNDID 1

#endif // ASSETS_CONSTANTS_H 
